#!/bin/sh
set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"
brew bundle

curl -fsSL https://mise.run | sh
~/.local/bin/mise trust
~/.local/bin/mise bootstrap dotfiles apply
~/.local/bin/mise install
