[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
duckdb = "latest"
postgres = "latest"
nodejs = "latest"
ruby = "latest"
pi = "latest"
direnv = "latest"
eza = "latest"
fzf = "latest"
neovim = "latest"
ripgrep = "latest"
tmux = "latest"
gh = "latest"

[bootstrap.packages]
"brew:openssl@3" = "latest"
"brew:icu4c@77" = "latest"
"brew:zlib" = "latest"
"brew:libyaml" = "latest"
"brew:vips" = "latest"
"brew:mole" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:slack" = "latest"
"brew-cask:whatsapp" = "latest"
"brew-cask:rectangle" = "latest"
"brew-cask:orbstack" = "latest"
"brew-cask:codex" = "latest"
"brew-cask:font-jetbrains-mono-nerd-font" = "latest"
